version: '3.9'
services:
   readme-551.blog.mongo:
     image: mongo:4.4
     restart: always
     container_name: readme-551.blog.mongo

     environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: test
       MONGO_INITDB_DATABASE: readme-551

     ports:
       - 27018:27018

     volumes:
       - readme-551.mongo.blog:/data/db

     healthcheck:
       test: echo 'db.runCommand("ping").ok' | mongosh localhost:27018/readme-551 --quiet
       interval: 10s
       timeout: 10s
       retries: 5

   readme-551.user.mongo.ui:
     image: mongo-express
     restart: always
     container_name: readme-551.user.mongo.ui
     ports:
       - 8081:8081
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
       ME_CONFIG_MONGODB_ADMINPASSWORD: test
       ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme-551.blog.mongo:27018/

volumes:
   readme-551.mongo.blog:
